### ISSUE TITLE
Login API

### ISSUE THREAD

**Issue by Neztore** [Quenty/ROBLOX-group-autoranker#1]
This will no longer work as ROBLOX removed the Login API.
In order for this to work you need figure out how to login via. the normal log-in screen, which I've been trying to do. This is difficult due to the lack of commenting and the poor readability of the code. Could you please tell me what the variable bot refers to? Thank you.

**The actual issue is that this just won't work without the old API.** @Quenty

**Comment by Neztore** [comment]
I've just looked and the function
`bot.setRole` does not appear to exist at ALL.

**Comment by Quenty** [comment]
setRole is defined in the mixin. Is this API, specified here, down? https://github.com/matthewdean/roblox-web-apis/blob/master/README.md#user-apis

**Comment by Neztore** [comment]
The **login** API you are using DOES NOT EXIST.

**Comment by jakedowns** [comment]
@Neztore , cool your jets, lol. Checkout server.js on my patch branch, it's all fixed up and working again with the v2 login API.

@Quenty thanks for a handy script, cheers mate

**Comment by Neztore** [comment]
Regardless, it's irritating when someone reads your issue and disregards it entirely. I long ago moved onto the much more capable and adaptable [roblox-js](https://github.com/sentanos/roblox-js).

**Comment by jakedowns** [comment]
@Neztore ah cool, I'll have to check that out
