### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by spiralgaia** [Quenty/ROBLOX-group-autoranker#4]
I dont fully trust you when it comes to the password thing. How do i know your 100% quenty! Also im stuck trying to know where to put the pass! I dont see a Auth.JSON File and if i did i cant edit it.

**Comment by Quenty** [comment]
You need to make an auth.json file and put the password in there. It's not included so you can't accidentally expose your credentials. You can read the code, so you should be able to trust it.
